[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_ENV = "production"
    HUGO_VERSION = "0.62.2"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "/*"
    to = "/404.html"
    status = 404

[[redirects]]
    from = "https://chflick.netlify.com/*"
    to = "https://www.christophflick.de/:splat"
    status = 301
    force = true
